services: 
  executable:
    container_name: miner
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./app_code:${CODE_DIRECTORY}
    env_file:
      - .env
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  vdb:
    container_name: qdrant-db
    image: qdrant/qdrant:v1.14.1
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - ./qdrant_storage:/qdrant/storage

