services: 
  executable:
    container_name: miner
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./app_code:${CODE_DIRECTORY}
      - hf_cache:/cache/hf
    env_file:
      - .env
    environment:
      - HF_HOME=/cache/hf
      - HF_HUB_CACHE=/cache/hf/hub
      - HF_DATASETS_CACHE=/cache/hf/datasets
      - HF_STREAM_CACHE=/cache/hf/stream   # dla streamingu (fsspec simplecache)
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  vdb:
    container_name: qdrant-db
    image: qdrant/qdrant:v1.14.1
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - ./qdrant_storage:/qdrant/storage
volumes:
  hf_cache: